const API='https://uzqlqihvgxnepmfjgxlh.supabase.co/functions/v1/submit-objection';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const ar='٠١٢٣٤٥٦٧٨٩';
const toArabic=v=>String(v??'').replace(/\d/g,d=>ar[d]);
const toLatin=v=>String(v??'').replace(/[٠-٩]/g,d=>String(ar.indexOf(d)));
const onlyDigits=v=>toLatin(v).replace(/\D/g,'');
const fmt=(iso,cal)=>{if(!iso)return 'يوم شهر سنة';const d=new Date(iso+'T12:00:00');return new Intl.DateTimeFormat('ar-SA-u-ca-'+(cal==='h'?'islamic-umalqura':'gregory'),{day:'numeric',month:'long',year:'numeric'}).format(d)};
const fmtAlt=(iso,cal)=>iso?`${cal==='h'?'الميلادي':'الهجري'}: ${fmt(iso,cal==='h'?'g':'h')}`:'';

function numericArabic(el,max,exact=false){el.addEventListener('input',()=>{const d=onlyDigits(el.value).slice(0,max);el.value=toArabic(d);el.setCustomValidity(exact&&d.length!==max?`يجب إدخال ${toArabic(max)} أرقام بالضبط`:'')});}
function arabicName(el){el.addEventListener('input',()=>{el.value=el.value.replace(/[^ء-ي\s]/g,'').replace(/\s{2,}/g,' ');el.setCustomValidity(el.value.trim().length<2?'الاسم يجب أن يكون باللغة العربية فقط':'')});}
function initDate(root){const mode=root.querySelector('.calendar-mode'),native=root.querySelector('.date-native'),text=root.querySelector('.date-text'),alt=root.querySelector('.date-alt');const paint=()=>{text.textContent=fmt(native.value,mode.value);alt.textContent=fmtAlt(native.value,mode.value)};native.addEventListener('change',paint);mode.addEventListener('change',paint);paint();}

const violationBody=$('#violationBody');let rowCount=0;
function violationRow(n){const required=n===1?'required':'';const row=document.createElement('div');row.className='violation-row';row.dataset.seq=n;row.innerHTML=`<div class="seq">${toArabic(n)}</div><div class="number"><input class="violation-no" inputmode="numeric" maxlength="10" placeholder="١٠ أرقام فقط" ${required}></div><div class="title"><input class="violation-title" maxlength="200" ${required}></div><div class="date"><div class="date-control"><select class="calendar-mode" aria-label="نوع التقويم"><option value="g">ميلادي</option><option value="h">هجري</option></select><label class="date-button"><span class="date-text">يوم شهر سنة</span><input class="date-native" type="date" ${required}></label><small class="date-alt"></small></div></div><div class="location"><input class="violation-location" maxlength="300" ${required}></div>`;numericArabic(row.querySelector('.violation-no'),10,n===1);initDate(row.querySelector('.date-control'));return row;}
function addViolation(){if(rowCount>=10)return;rowCount++;violationBody.appendChild(violationRow(rowCount));$('#removeViolation').disabled=rowCount<=4;$('#addViolation').disabled=rowCount>=10;if(rowCount>4)violationBody.lastElementChild.scrollIntoView({behavior:'smooth',block:'center'});}
function removeViolation(){if(rowCount<=4)return;violationBody.lastElementChild.remove();rowCount--;$('#removeViolation').disabled=rowCount<=4;$('#addViolation').disabled=false;}
for(let i=0;i<4;i++)addViolation();$('#addViolation').addEventListener('click',addViolation);$('#removeViolation').addEventListener('click',removeViolation);
$$('.date-control').forEach(initDate);

const fullName=$('#fullName'),footerName=$('#footerName'),identity=$('#identityNo'),phone=$('#phone'),recordNo=$('#recordNo');arabicName(fullName);fullName.addEventListener('input',()=>footerName.value=fullName.value);numericArabic(identity,10,true);numericArabic(phone,10,true);numericArabic(recordNo,10,false);$$('.plate-num').forEach(x=>numericArabic(x,1,true));$$('.plate-letter').forEach(x=>x.addEventListener('input',()=>{x.value=x.value.replace(/[^ء-يA-Za-z]/g,'').slice(0,1)}));
function autoAdvance(selector){const a=$$(selector);a.forEach((el,i)=>{el.addEventListener('input',()=>{if(el.value&&a[i+1])a[i+1].focus()});el.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!el.value&&a[i-1])a[i-1].focus()})})}autoAdvance('.plate-num');autoAdvance('.plate-letter');

const emergency=$('#emergency');function syncEmergency(){const on=emergency.checked;['hospitalName','hospitalDate','patientName','recordNo'].forEach(id=>{const el=$('#'+id);el.disabled=!on;el.required=on;if(!on&&el.type!=='date')el.value=''});$('#emergencyFields').classList.toggle('hidden',!on)}emergency.addEventListener('change',syncEmergency);syncEmergency();

function makePad(canvas,clear){const ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';let drawing=false,signed=false;const p=e=>{const r=canvas.getBoundingClientRect(),q=e.touches?e.touches[0]:e;return{x:(q.clientX-r.left)*canvas.width/r.width,y:(q.clientY-r.top)*canvas.height/r.height}};const start=e=>{e.preventDefault();drawing=true;const q=p(e);ctx.beginPath();ctx.moveTo(q.x,q.y)};const move=e=>{if(!drawing)return;e.preventDefault();const q=p(e);ctx.lineTo(q.x,q.y);ctx.stroke();signed=true};const end=()=>drawing=false;canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',end);canvas.addEventListener('mouseleave',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);clear.addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false});return{has:()=>signed,data:()=>canvas.toDataURL('image/png'),reset:()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false}}}
const pad=makePad($('#citizenSignature'),$('#clearSignature'));

function collectViolations(){const rows=$$('.violation-row');const list=[];let gap=false;for(const [i,row] of rows.entries()){const no=row.querySelector('.violation-no'),title=row.querySelector('.violation-title'),date=row.querySelector('.date-native'),loc=row.querySelector('.violation-location');const any=[no.value,title.value,date.value,loc.value].some(v=>String(v).trim());if(i===0||any){if(gap){no.setCustomValidity('يجب إدخال المخالفات بالتسلسل دون ترك صف فارغ');no.reportValidity();return null}const n=onlyDigits(no.value);if(n.length!==10){no.setCustomValidity('رقم المخالفة يجب أن يكون ١٠ أرقام بالضبط');no.reportValidity();return null}no.setCustomValidity('');if(!title.value.trim()){title.setCustomValidity('نوع المخالفة مطلوب');title.reportValidity();return null}title.setCustomValidity('');if(!date.value){date.setCustomValidity('تاريخ المخالفة مطلوب');date.reportValidity();return null}date.setCustomValidity('');if(!loc.value.trim()){loc.setCustomValidity('موقع المخالفة مطلوب');loc.reportValidity();return null}loc.setCustomValidity('');list.push({violation_no:n,violation_title:title.value.trim(),violation_date:date.value,violation_location:loc.value.trim()})}else if(list.length)gap=true}return list;}

const form=$('#citizenForm'),status=$('#status'),submitBtn=$('#submitBtn');form.addEventListener('submit',async e=>{e.preventDefault();status.textContent='';if(!form.reportValidity())return;if(!/^[ء-ي\s]{2,150}$/.test(fullName.value.trim())){fullName.setCustomValidity('الاسم باللغة العربية فقط');fullName.reportValidity();return}const violations=collectViolations();if(!violations||!violations.length)return;if(!pad.has()){status.textContent='التوقيع الإلكتروني مطلوب قبل الإرسال.';return}const plateNumbers=$$('.plate-num').map(x=>onlyDigits(x.value)).join('');const plateLetters=$$('.plate-letter').map(x=>x.value.trim()).join(' ');if(plateNumbers.length!==4||plateLetters.replace(/\s/g,'').length!==3){status.textContent='أكمل أرقام وحروف اللوحة.';return}const payload={full_name:fullName.value.trim(),identity_no:onlyDigits(identity.value),nationality:$('#nationality').value.trim(),memo_date:$('#memoDate').value,plate_numbers:plateNumbers,plate_letters:plateLetters,vehicle_type:$('#vehicleType').value.trim(),violation_no:violations[0].violation_no,violation_date:violations[0].violation_date,violation_title:violations[0].violation_title,violation_location:violations[0].violation_location,violations,objection_text:$('#objectionText').value.trim(),citizen_signature:pad.data(),phone:onlyDigits(phone.value),emergency:emergency.checked,hospital_name:emergency.checked?$('#hospitalName').value.trim():'',hospital_date:emergency.checked?$('#hospitalDate').value:'',patient_name:emergency.checked?$('#patientName').value.trim():'',medical_record_no:emergency.checked?onlyDigits(recordNo.value):'',decision_no:'',decision_date:'',website:$('#website').value};submitBtn.disabled=true;submitBtn.textContent='جارٍ الإرسال...';status.textContent='يرجى الانتظار حتى يتم حفظ الاعتراض.';try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const out=await res.json();if(!res.ok||!out.ok)throw new Error(out.error||'send');const ref=toArabic(out.reference);$('#objectionRef').value=ref;$('#successRef').textContent=ref;$('#success').style.display='block';status.textContent='تم إرسال الاعتراض بنجاح.';submitBtn.textContent='تم الإرسال';form.querySelectorAll('input,select,textarea,button').forEach(el=>{if(!['printBtn'].includes(el.id))el.disabled=true});$('#success').scrollIntoView({behavior:'smooth'})}catch(err){status.textContent='تعذر إرسال الاعتراض. تحقق من البيانات والاتصال ثم حاول مرة أخرى.';submitBtn.disabled=false;submitBtn.textContent='إرسال الاعتراض'}});

$('#resetBtn').addEventListener('click',()=>{form.reset();while(rowCount>4)removeViolation();$$('.violation-row').forEach((r,i)=>{r.querySelectorAll('input').forEach(x=>x.value='');r.querySelectorAll('select').forEach(x=>x.value='g');r.querySelector('.date-text').textContent='يوم شهر سنة';r.querySelector('.date-alt').textContent=''});footerName.value='';$('#objectionRef').value='';$('#success').style.display='none';status.textContent='';pad.reset();syncEmergency()});$('#printBtn').addEventListener('click',()=>window.print());