import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const sb=createClient('https://uzqlqihvgxnepmfjgxlh.supabase.co','sb_publishable_iKlB3hRgacOcBme3R6zfiw_cQtC8ib8',{auth:{persistSession:true,autoRefreshToken:true}});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ar='٠١٢٣٤٥٦٧٨٩';
const toArabic=v=>String(v??'').replace(/\d/g,d=>ar[d]);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>v?new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v+'T12:00:00')):'—';
const statusName=s=>({new:'جديد',valid:'صحيحة',cancelled:'إلغاء',code_edit:'تعديل رمز',transfer:'تحويل',letter:'خطاب'}[s]||s||'جديد');
let requests=[],violations={},current=null;

function signaturePad(canvas,clearBtn){const ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';let draw=false,signed=false;const point=e=>{const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}};const start=e=>{e.preventDefault();draw=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!draw)return;e.preventDefault();const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();signed=true};const end=()=>draw=false;canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);canvas.addEventListener('mouseup',end);canvas.addEventListener('mouseleave',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);clearBtn.addEventListener('click',()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false});return{has:()=>signed,data:()=>canvas.toDataURL('image/png'),clear:()=>{ctx.clearRect(0,0,canvas.width,canvas.height);signed=false}}}
const empPad=signaturePad($('#employeeSignature'),$('#clearEmployeeSignature'));

async function enter(){document.body.classList.remove('login-mode');$('#authPanel').classList.add('hidden');$('#app').classList.remove('hidden');$('#logout').classList.remove('hidden');await loadRequests()}
async function loadRequests(){const list=$('#requestList');list.innerHTML='جارٍ التحميل...';const {data,error}=await sb.from('objections').select('*').order('created_at',{ascending:false}).limit(500);if(error){list.innerHTML='<div class="message">غير مصرح لهذا الحساب أو تعذر تحميل الاعتراضات.</div>';return}requests=data||[];violations={};const ids=requests.map(x=>x.id);if(ids.length){const {data:v,error:ve}=await sb.from('objection_violations').select('*').in('objection_id',ids).order('seq',{ascending:true});if(ve){list.innerHTML='<div class="message">تعذر تحميل تفاصيل المخالفات.</div>';return}(v||[]).forEach(x=>(violations[x.objection_id]??=[]).push(x))}renderList()}
function renderList(){const q=$('#search').value.trim().toLowerCase(),filter=$('#filter').value;const rows=requests.filter(r=>{const child=(violations[r.id]||[]).map(v=>v.violation_no).join(' ');return(!filter||r.status===filter)&&(!q||[r.reference_no,r.full_name,r.identity_no,r.violation_no,child].some(x=>String(x||'').toLowerCase().includes(q))) });$('#requestList').innerHTML=rows.length?rows.map(r=>`<article class="request" data-id="${r.id}"><strong>اعتراض رقم ${toArabic(r.reference_no)}</strong> — ${esc(r.full_name)}<div class="meta">${toArabic((violations[r.id]||[]).length||1)} مخالفة · ${new Date(r.created_at).toLocaleString('ar-SA')} · <span class="badge">${statusName(r.status)}</span></div></article>`).join(''):'لا توجد نتائج.';$$('.request').forEach(x=>x.addEventListener('click',()=>openRequest(x.dataset.id)))}
function row(label,value,span=false){return `<tr><th>${label}</th><td${span?' colspan="3"':''}>${esc(value||'—')}</td>${span?'':' '}</tr>`}
function openRequest(id){current=requests.find(x=>x.id===id);if(!current)return;const vs=violations[id]?.length?violations[id]:[{seq:1,violation_no:current.violation_no,violation_title:current.violation_title,violation_date:current.violation_date,violation_location:current.violation_location}];$('#listPanel').classList.add('hidden');$('#detailView').classList.remove('hidden');$('#refNo').textContent=toArabic(current.reference_no);$('#memoDate').textContent=fmtDate(current.memo_date||current.created_at?.slice(0,10));$('#personRows').innerHTML=`<tr><th>الاسم</th><td>${esc(current.full_name)}</td><th>رقم الهوية/الإقامة</th><td>${toArabic(current.identity_no)}</td></tr><tr><th>الجنسية</th><td>${esc(current.nationality)}</td><th>رقم الجوال</th><td>${toArabic(current.phone||'—')}</td></tr>`;$('#violationRows').innerHTML=vs.map(v=>`<tr><td class="center">${toArabic(v.seq)}</td><td>${toArabic(v.violation_no)}</td><td>${esc(v.violation_title)}</td><td>${fmtDate(v.violation_date)}</td><td>${esc(v.violation_location)}</td></tr>`).join('');$('#vehicleRows').innerHTML=`<tr><th>رقم اللوحة</th><td>${toArabic(current.plate_numbers)} ${esc(current.plate_letters)}</td><th>نوع المركبة</th><td>${esc(current.vehicle_type)}</td></tr><tr><th>رقم القرار الإلكتروني</th><td>${toArabic(current.decision_no||'—')}</td><th>تاريخ القرار</th><td>${fmtDate(current.decision_date)}</td></tr>`;$('#medicalRows').innerHTML=current.emergency?`<tr><th>حالة إسعافية طارئة</th><td>نعم</td><th>اسم المستشفى</th><td>${esc(current.hospital_name||'—')}</td></tr><tr><th>اسم المريض</th><td>${esc(current.patient_name||'—')}</td><th>رقم السجل</th><td>${toArabic(current.medical_record_no||'—')}</td></tr><tr><th>تاريخ المستشفى</th><td colspan="3">${fmtDate(current.hospital_date)}</td></tr>`:`<tr><th>حالة إسعافية طارئة</th><td colspan="3">لا</td></tr>`;$('#reasonText').textContent=current.objection_text||'';$('#citizenName').textContent=current.full_name||'—';$('#citizenPhone').textContent=toArabic(current.phone||'—');$('#citizenSignature').src=current.citizen_signature||'';$('#citizenSignature').classList.toggle('hidden',!current.citizen_signature);$$('input[name="employeeAction"]').forEach(x=>x.checked=x.value===current.status);$('#violationNotes').value=current.violation_notes||'';$('#actionTaken').value=current.action_taken||'';empPad.clear();$('#saveStatus').textContent='';$('#detailView').scrollIntoView({behavior:'smooth',block:'start'})}

$('#login').addEventListener('click',async()=>{const email=$('#email').value.trim(),password=$('#password').value;$('#authMessage').textContent='';const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('#authMessage').textContent='بيانات الدخول غير صحيحة.';return}await enter()});
$('#setup').addEventListener('click',async()=>{const email=$('#email').value.trim(),password=$('#password').value;$('#authMessage').textContent='جارٍ إنشاء الحساب الأول...';try{const r=await fetch('https://uzqlqihvgxnepmfjgxlh.supabase.co/functions/v1/employee-bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const o=await r.json();$('#authMessage').textContent=r.ok&&o.ok?'تم إنشاء الحساب. اضغط دخول.':o.error==='setup_closed'?'تم إنشاء حساب الموظف مسبقًا. استخدم تسجيل الدخول.':'تعذر إنشاء الحساب. استخدم بريدًا صحيحًا وكلمة مرور ١٢ حرفًا على الأقل.'}catch{$('#authMessage').textContent='تعذر الاتصال.'}});
$('#logout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});$('#refresh').addEventListener('click',loadRequests);$('#search').addEventListener('input',renderList);$('#filter').addEventListener('change',renderList);$('#back').addEventListener('click',()=>{$('#detailView').classList.add('hidden');$('#listPanel').classList.remove('hidden');current=null;window.scrollTo({top:0,behavior:'smooth'})});$('#print').addEventListener('click',()=>window.print());

$('#save').addEventListener('click',async()=>{if(!current)return;const action=$('input[name="employeeAction"]:checked');if(!action){$('#saveStatus').textContent='اختر الإجراء أولًا.';return}if(!$('#violationNotes').value.trim()){$('#saveStatus').textContent='حيثيات المخالفة مطلوبة.';return}if(!$('#actionTaken').value.trim()){$('#saveStatus').textContent='اسم متخذ الإجراء مطلوب.';return}if(!empPad.has()){$('#saveStatus').textContent='توقيع الموظف مطلوب.';return}const {data:{user}}=await sb.auth.getUser();$('#save').disabled=true;$('#saveStatus').textContent='جارٍ الحفظ...';const payload={status:action.value,action_code:action.value,violation_notes:$('#violationNotes').value.trim().slice(0,5000),action_taken:$('#actionTaken').value.trim().slice(0,200),employee_signature:empPad.data(),employee_signed_at:new Date().toISOString(),employee_signed_by:user?.id||null,employee_recommendation:action.value,employee_submitted_at:new Date().toISOString(),workflow_stage:'committee'};const {error}=await sb.from('objections').update(payload).eq('id',current.id);$('#save').disabled=false;if(error){$('#saveStatus').textContent='تعذر حفظ الإجراء.';return}$('#saveStatus').textContent='تم حفظ الإجراء وإرساله للجنة.';Object.assign(current,payload);await loadRequests()});

const {data:{session}}=await sb.auth.getSession();if(session)enter();else document.body.classList.add('login-mode');